// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 2);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1704322275);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1704322275);
user_pref("app.update.lastUpdateTime.region-update-timer", 1704322275);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1704322275);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1704322304);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1704322275);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{dabb9267-b2dd-4542-9a38-3e98d6ede0ab}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1704322245);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{55b6afac-ec0a-487a-abb7-34ab8a41ddd0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "always");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1704322252);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1704322291601");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1704324117601");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1704322267329");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1704343867329");
user_pref("browser.search.region", "PT");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230724124053");
user_pref("browser.startup.homepage_override.mstone", "115.1.0");
user_pref("browser.startup.lastColdStartupCheck", 1704322249);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.topsites.contile.lastFetch", 1704323642);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "115.1.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "PT");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "039f3cfe5d9641048cacd6510e571dcb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1704322276);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230724124053");
user_pref("extensions.lastAppVersion", "115.1.0");
user_pref("extensions.lastPlatformVersion", "115.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b2d01ac2-b700-43cf-a308-19d05b93d7c3\",\"pictureinpicture@mozilla.org\":\"7ceae39b-24da-4f9e-adcb-59bcd4b2e744\",\"screenshots@mozilla.org\":\"edd5e924-55bf-4d7c-9a41-edd3d1a1f99d\",\"webcompat-reporter@mozilla.org\":\"770dc244-db21-43d5-9b6f-4b4e79b405df\",\"webcompat@mozilla.org\":\"ee33fb21-a3fa-4d43-90f3-64015816a374\",\"default-theme@mozilla.org\":\"223a5e4c-2d85-4b44-9499-96ec9ae4efbe\",\"addons-search-detection@mozilla.com\":\"88475dd8-c702-4687-8cdb-64fa759e3902\",\"google@search.mozilla.org\":\"7f649d28-09a5-4b71-ae74-206862fd8105\",\"wikipedia@search.mozilla.org\":\"24ebfa0f-6a07-48d6-85a3-154adfdc547e\",\"bing@search.mozilla.org\":\"3157902c-94a3-4471-b6db-486ece0dcc69\",\"ddg@search.mozilla.org\":\"0389ceb8-e45a-4950-aa30-954d2a5c17a3\",\"amazon@search.mozilla.org\":\"3e1a3998-47cd-4da6-8718-5cae10ac00b2\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1704322628);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "53a58bfb4c8124ad4f7655b99bfdea290033a085e0796b19245b33b91c0948fdac9f0c3e817130b352493a65d9a7a0fc8a7c1eedc618cdaa2b4580734a11cd9c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1704322278);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1704322277);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1704322279);
user_pref("media.gmp-gmpopenh264.version", "2.3.2");
user_pref("media.gmp-manager.buildID", "20230724124053");
user_pref("media.gmp-manager.lastCheck", 1704322366);
user_pref("media.gmp-manager.lastEmptyCheck", 1704322366);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1704322629);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1704322628604");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "274bc596-d59f-4ed5-8b7d-7649d00e856e");
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_update_seconds", 1704322367);
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1704322628);
user_pref("toolkit.startup.last_success", 1704322241);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230724124053");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
